encoding: utf-8

# Site settings
title: 我自闭了
motto: 最不发达国家
motto_link: 1
email: ldcc@live.com
description: a blog for writing gibberish
baseurl: ""
res: "/res/"
url: "https://ldcc.github.io/"
github: ldcc
gitlab: ldcc
twitter: ldcdroid

# Others plugin or configuration
markdown: kramdown
kramdown:
  math_engine: mathjax