encoding: utf-8

# Site settings
title: 想找女朋友
email: ldcc@live.com
author: ldc
description: A blog for writing gibberish
baseurl: ''
url: https://ldcc.github.io/
favicon: /assets/icons/favicon.png
res: /assets/
github: ldcc
twitter: ldcc
excerpt_separator: "\n"

# Others plugin or configuration
markdown: kramdown
kramdown:
  math_engine: mathjax