encoding: utf-8

# Site settings
title: 我自闭了
email: ldcc@live.com
author: ldc
description: A blog for writing gibberish
baseurl: ''
url: https://ldcc.github.io/
favicon: /assets/icons/favicon.png
res: /assets/
github: ldcc
twitter: ldcdroid

# Others plugin or configuration
markdown: kramdown
kramdown:
  math_engine: mathjax