encoding: utf-8

# Site settings
title: 我自闭了
motto: 最不发达国家
motto_link: 1
email: ldcc@live.com
description: a blog for writing gibberish
res: "/resources/"
url: "https://ldcc.github.io/"
twitter_username: ldcdroid
github_username: ldcc

# Others plugin or configuration
markdown: kramdown
